openapi: 3.0.2
info:
  description: Device Maintenance - Get daily password valid for the day
  version: '1.0'
  title: Device Maintenance - Get daily password valid for the day
  termsOfService: 'urn:tos'
  contact: {}
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0'
servers:
  - url: 'https://cat.api.firstdata.com'
x-header-api-key: X0GW3QGOYFn4r7DHcVC8KuatUnNs6MGB
x-header-api-secret: N93nmFmoY0NzSMC5
x-production-url: prod.api.firstdata.com
x-config:
  tryItOut: true
tags:
  - name: Get daily password valid for the day
paths:
  "/bwa/senha-dia/v1/senha/dia":
    get:
      tags:
        - Device Maintenance
      x-proxy-name: Merchant Devices Daily Password - Consult
      x-group-name: Devices Information
      x-child-product-name: Banworks
      description: Get daily password valid for the day
      summary: Get Daily Passorword Valid for the Day
      operationId: getDailyPassword
      parameters:
        - name: Message-Signature
          in: header
          description: HMAC
          required: true
          example: 1tsmkG9Ip3k2rcO5cETButfP3D/RS6U8troFF+mUrno=
          schema:
            type: string
        - name: Api-Key
          in: header
          description: APigee Key
          required: true
          example: X0GW3QGOYFn4r7DHcVC8KuatUnNs6MGB'
          schema:
            type: string
        - name: auth
          in: header
          description: Oauth Key
          required: true
          example: null
          schema:
            type: string
        - name: Timestamp
          in: header
          description: Date - Epoch Format
          required: true
          example: 1563309156733
          schema:
            type: string
        - name: Client-Request-Id
          in: header
          description: Randomly generated by client
          required: true
          example: 6NYHj9Pgyxc84rmafpwG4fjhLwFfJYFVmxJOcgziD0QN3q6mGC
          schema:
            type: string
        - name: instituicao
          in: header
          description: Merchant Institution Number
          example: "00000003"
          required: true
          schema:
            type: string
        - name: documento
          in: header
          description: CPF / CNPJ
          example: "74185296387"
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
        '206':
          description: Partial Content
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PartialContent'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Unauthorized'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Forbidden'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFound'
        '409':
          description: Conflict
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Conflict'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
      deprecated: false
components:
  schemas:
    Response:
      type: object
      properties:
        codigoRetorno:
          type: integer
          description: Return Status Code
          example: '0'
          enum: 
            - 0
            - 1
        mensagem:
          type: string
          description: Return Description Message
          example: Sucesso
          enum: 
           - 0 - Successo.
           - 1 - Error
        senhaDia:
          type: string
          description: Return Daily Password
          example: 04058100
    PartialContent:
      type: object
      properties:
        codigoRetorno:
          description: Return Code
          example: 9
          type: integer
          format: int32
          enum: 
            - 9
            - 10
        mensagem:
          description: Description return code
          example: Campos mandatorios (meaning mdantory Fields Missing)
          type: string
          enum: 
            - "9 - Campos mandatorios - (meaning Mandatory Fields Missing"
            - "10 - (Erro validaçao) - (meaning Validation Error)"
    Unauthorized:
      type: object
      properties:
        codigoRetorno:
          description: Return Code
          example: 4
        mensagem:
          description: Description return code
          example: Acesso nao autorizado ao conteudo pesquisado - (meaning Unauthorized Access)
          type: string
    Forbidden:
      type: object
      properties:
        codigoRetorno:
          description: Return Code
          example: 3
          type: integer
          format: int32
          enum: 
            - 3
            - 6
        mensagem:
          description: Description return code
          example: Acesso negado- (meaning Access Denied)
          type: string
          enum: 
            - "3 - Acesso negado - (meaning Access Denied)"
            - "6 - Token expirado - (meaning Expired Token)"
    NotFound:
      type: object
      properties:
        codigoRetorno:
          description: Return Code
          example: 5
        mensagem:
          description: Description return code
          example: Item nao encontrado - (meaning Item not Found)
          type: string
    Conflict:
      type: object
      properties:
        codigoRetorno:
          description: Return Code
          example: 8
        mensagem:
          description: Description return code
          example: Item duplicado - (meaning Item Duplicated)
          type: string
    InternalServerError:
      type: object
      properties:
        codigoRetorno:
          description: Return Code
          example: 2
          type: integer
          format: int32
          enum: 
            - 2
            - 7
        mensagem:
          description: Description return code
          example: Erro Interno - (meaning Internal Error)
          type: string
          enum: 
            - "2 - Erro Interno - (meaning Internal Error)"
            - "7 - Erro na integracao da API. Detalhe - (meaning API Integration Error)"
