openapi: 3.0.2
info:
  title: Consult the Merchant Monthly Presumed Billing
  description: Consult the Merchant Monthly Presumed Billing
  termsOfService: 'urn:tos'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0'
  version: 2.0.0
x-header-api-key: X0GW3QGOYFn4r7DHcVC8KuatUnNs6MGB
x-config:
  tryItOut: true
x-header-api-secret: N93nmFmoY0NzSMC5
x-production-url: 'prod.api.firstdata.com'
servers:
  - url: 'https://cat.api.firstdata.com'
    variables: {}
paths:
  /bwa/merchant-billing/monthly/presumed:
    get:
      tags:
        - Consult the Merchant Monthly Presumed Billing
      x-proxy-name: Merchant Information - Monthly Presumed Billing
      x-group-name: Merchant Information & Cases
      x-child-product-name: Digital Solutions
      description: Consult the Merchant Monthly Presumed Billing
      operationId: Consult the Merchant Monthly Presumed Billing
      parameters:
        - name: auth
          in: header
          description: Oauth Key
          required: true
          schema:
            type: string
            example: eyJhbGaiOiJSUzI1NiasInR5cCIgOiAiSlaUIiwia0lkIiA6ICIz0VdqaW5TNHQ4eUhQSkVqdG91MW9CQ2c0U1lUWHNBMllUM2kyU0o4UXJZIn0.eyJqdGkiOiI1N2NiNmUzNy1lNzc0LTQwODQtYjQ4ZC05ZGYzNzBiZWQ2ZmEiLCJleHAiOjE2NTM0MjAwODksIm5iZiI6MCwiaWF0IjoxNTkxMjEyMDg5LCJpc3MiOiJodHRwczovL3JhY3Z3YjEwMDEuMWRjLmNvbS9hdXRoL3JlYWxtcy9GaXJzdERhdGEiLCJhdWQiOiJ0bXMtc2IiLCJzdWIiOiJiNDU5ZTU0Yi1kZDk4LTQzMTUtYmM2Yy00Njg0Mjk2MjhhMWYiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJ0bXMtc2IiLCJhdXRoX3RpbWUiOjAsInNlc3Npb25fc3RhdGUiOiI1MmNmMzEwNC0zYzIyLTQ2ZjAtYTljOS04ZmUzMjM2ZDgwZDQiLCJhY3IiOiIxIiwiY2xpZW50X3Nlc3Npb24iOiIyNmVlNDg2Yy0yMDU1LTQ1OTItODc4Ny0xOTFhYTBhOWE4NDYiLCJhbGxvd2VkLW9yaWdpbnMiOlsiaHR0cDovL3JhY3Z3YjEwMDEuMWRjLmNvbS90bXMtc2IvIiwiaHR0cHM6Ly9yYWN2d2IxMDAxLjFkYy5jb20vdG1zLXNiLyJdLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsiVkFMSURBVE9SIiwiRE9NSUNJTElPQkFOQ0FSSU8iLCJTSUNSRUQiLCJIVUlBIiwiU0lDUkVESSIsIkNPTlNVTFRBX0NQRl9DTlBKIiwiQ1JFRElDQVJEIiwiQ0VQIiwiZGlsaWdlbmNlIiwiUkVERSIsIlNFTkRfRU1BSUwiLCJGSVJTVERBVEEiLCJ2YW5ib2FyZGluZyIsIkdBX0ZpcnN0RGF0YSIsIkdBX0l0ZXJpcyIsIkdPT0dMRSIsIkRBRE9TX0xPR0lTVElDQSIsIkJBTkNPT0IiXX0sInJlc291cmNlX2FjY2VzcyI6eaaJhY2NvdW50Ijp7InJvbGVzIjabImahbmFnZS1hY2NvdW50IiwibWFuYWalLWFjYa91bnQtbGlua3MiLCJ2aWV3LXByb2ZpbGUiXX19LCJuYW1lIjoiIiwicHJlZmVycmVkX3VzZXJuYW1lIjoic2VydmljZTM2MCJ9.dELgls0MlwpQ9MgtxLYLr8PLpY16VMuPlXnhB-UL4WFiUaaECwbicH7mvL8UD7Bf84jp7SlAW8axkeePCSLF4aF1jVMOmmNGvfy8kQN4Zag52qoaaFA5cxGpHK9FnfXLrxf6kqaUNB2aohnEcWoo098OuxoufZ2Rq7h55EygkaPSXkuHKEvbc2ZRlBpgyQrXbB02uaasUuvJ8Eens1-dxU6iY6CSX0sMaI6CaiETW5Qdxab4OGkNL-aK4bKjo7I-Iayg9OTvzyZXhn5LflQgar8gF_zFB-XfVKnEn-R1SGvCCatu0-F8WWjFo6NzXbxfq2SOy3YGOg46fokLVtSNF2br
        - name: Api-Key
          in: header
          description: APIGEE key
          required: true
          schema:
            type: string
            example: X0GW3QGOYFn4r7DHcVC8KuatUnNs6MGB
        - name: Timestamp
          in: header
          description: Date in EPOCH format
          required: true
          schema:
            type: string
            example: 1591212089576
        - name: Message-Signature
          in: header
          description: HMAC
          required: true
          schema:
            type: string
            example: MzgzYTIxZjJjYTI1NmE2ZGM2OTE3YTkzZjU5YTY0Zjk2NjAzMmUxMTZjOTJlMDU1ZWExOGU4MzJhMzc2NjQwOA==
        - name: Client-Request-Id
          in: header
          description: Ramdom string generated by the client
          required: true
          schema:
            type: string
            example: H7MZvxxy2qWfc5gxScXQYC2tyaWZ8
        - name: instituicao
          in: header
          description: The institution number
          required: true
          schema:
            type: string
            example: '00000003'
        - name: service-contract
          in: header
          description: The service contract ID
          required: true
          schema:
            type: string
            example: 101
        - name: merchant
          in: header
          description: The merchant number
          required: true
          schema:
            type: string
            example: 33785866
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DResponseDFaturamento'
        '400':
          description: BAD REQUEST - Invalid parameter
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DResponseDApiErro'
        '404':
          description: NOT FOUND - Billing not found for the given institution/service-contract/merchant
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DResponseDApiErro'
components:
  schemas:
    DApiErro:
      type: object
      properties:
        timestamp:
          type: string
          description: 'Request date in format yyyy-MM-dd HH:mm:ss'
          example: '2020-02-02 20:00:02'
        status:
          type: integer
          description: HTTP code
          format: int32
          example: 404
        error:
          type: string
          description: HTTP code description
          example: Not Found
        message:
          type: string
          description: Error message
          example: The requested resource was not found
        path:
          type: string
          description: URI
          example: /merchant-billing/monthly/presumed
      description: Return body
    DResponseDApiErro:
      type: object
      properties:
        returncode:
          type: integer
          description: 'Return code (0 for success, 1 for error)'
          format: int32
          example: 0
          enum:
            - 0
            - 1
        message:
          type: string
          description: 'Return message, describe the error when the return code is 1'
          example: The requested resource was not found
        content:
          $ref: '#/components/schemas/DApiErro'
    DFaturamento:
      type: object
      properties:
        institution:
          type: string
          description: Institution number
          example: '00000003'
        merchant:
          type: string
          description: Merchant number
          example: '33785866'
        serviceContract:
          type: string
          description: Service Contract ID. Please ask your Fiserv Representative, in case you don't have this information
          example: '101'
        billing:
          type: string
          example: 000000000012000.00
          description: Merchant Monthly Presumed Billing
      description: Return body
    DResponseDFaturamento:
      type: object
      properties:
        returncode:
          type: integer
          description: 'Return code (0 for success, 1 for error)'
          format: int32
          example: 0
          enum:
            - 0
            - 1
        message:
          type: string
          description: 'Return message, describe the error when the return code is 1'
          example: The requested resource was not found
        content:
          $ref: '#/components/schemas/DFaturamento'
