openapi: 3.0.2
info:
  description: Merchant Trade Name Update
  version: "1.0"
  title: Merchant Trade Name Update
  termsOfService: urn:tos
  contact: {}
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0
servers:
  - url: https://cat.api.firstdata.com
x-header-api-key: 'X0GW3QGOYFn4r7DHcVC8KuatUnNs6MGB'
x-header-api-secret: 'N93nmFmoY0NzSMC5'
x-production-url: prod.api.firstdata.com
x-config:
  tryItOut: true
tags:
  - name: Merchant Trade Name Update
paths:
  "/bwa/wsm/merchantinformation/tradeName/updateTradeName/":
    post:
      tags:
        - Merchant Trade Name Update
      x-proxy-name: Merchant Trade Name - Update
      x-group-name: Merchant Information & Cases
      x-child-product-name: Banworks
      description: Merchant Trade Name - Update
      summary: Merchant Information & Cases
      operationId: mechantTradeNameUpdate
      parameters:
        - name: Message-Signature
          in: header
          description: HMAC
          required: true
          example: 1tsmkG9Ip3k2rcO5cETButfP3D/RS6U8troFF+mUrno=
          schema:
            type: string
        - name: Api-Key
          in: header
          description: APigee Key
          required: true
          example: X0GW3QGOYFn4r7DHcVC8KuatUnNs6MGB
          schema:
            type: string
        - name: auth
          in: header
          description: Oauth Key
          required: true
          example:
          schema:
            type: string
        - name: Timestamp
          in: header
          description: Date - Epoch format
          required: true
          example: 1563309156733
          schema:
            type: string
        - name: Client-Request-Id
          in: header
          description: Randomly generated by client
          required: true
          example: 6NYHj9Pgyxc84rmafpwG4fjhLwFfJYFVmxJOcgziD0QN3q6mGC
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Body"
        description: body
        required: true
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Response"
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Unauthorized'
components:
  schemas:
    updateTradeName:
      type: object
      required:
        - institutionNumber
        - merchantID
        - tradeName
      properties:
        institutionNumber:
          type: string
          description: Merchant Institution Number
          example: "00000003"
        merchantID:
          type: string
          description: Merchant Code
          example: "91002806"
        tradeName:
          type: string
          description: Merchant Trade Name to be Updated
          example: "Nome Fantasia da Empresa"
    Body:
      type: object
      properties:
        updateTradeName:
          type: array
          items:
            $ref: "#/components/schemas/updateTradeName"
    responseInformationList:
      type: object
      properties:
        responseCode:
          type: string
          description: Return Code
          example: "00"
          enum:
            - 00 - Atualização realizada com sucesso. -(meaning Updated Successfully Done)
            - 01 - Atualização realizada com sucesso, mas mensagem UNS não enviada - (meaning Update Successfully done without UNS)
            - 02 - Parâmetros inválidos - (meaning Invalid Parameters)
            - 03 - Instituição/Estabelecimento Comercial não existe - (meaning Merchant Does not Exist)
            - 04 - Erro Interno no sistema - (meaning Error System)
            - 05 - Atualização rejeitada pelos sistemas TMS/FHM - (meaning Updated not confirmed)
            - 06 - Informações mandatórias não enviadas - (meaning Required Information not Provided)
            - 07 - Estabelecimento Comercial não Ativo/Suspenso - (meaning (Merchaint is not active or suspended)
            - 99 - Erro de Sistema - (meaning System Error)
        responseCodeDesc:
          type: string
          description: Return Code Description
          enum:
            - 00 - Atualização realizada com sucesso. -(meaning Updated Successfully Done)
            - 01 - Atualização realizada com sucesso, mas mensagem UNS não enviada - (meaning Update Successfully done without UNS)
            - 02 - Parâmetros inválidos - (meaning Invalid Parameters)
            - 03 - Instituição/Estabelecimento Comercial não existe - (meaning Merchant Does not Exist)
            - 04 - Erro Interno no sistema - (meaning Error System)
            - 05 - Atualização rejeitada pelos sistemas TMS/FHM - (meaning Updated not confirmed)
            - 06 - Informações mandatórias não enviadas - (meaning Required Information not Provided)
            - 07 - Estabelecimento Comercial não Ativo/Suspenso - (meaning (Merchaint is not active or suspended)
            - 99 - Erro de Sistema - (meaning System Error)
    response:
      type: object
      properties:
        responseInformationList:
          type: array
          items:
            $ref: "#/components/schemas/responseInformationList"
    processMessage:
      type: object
      properties:
        institutionNumber:
          type: string
          description: Merchant Institution Number
          example: "00000003"
        merchantID:
          type: string
          description: Merchant Code
          example: "91002806"
        tradeName:
          type: string
          description: Merchant Trade Name
          example: "Nome Fantasia da Empresa"
        response:
          $ref: "#/components/schemas/response"
    Response:
      type: object
      properties:
        processMessage:
          type: array
          items:
            $ref: "#/components/schemas/processMessage"
    Unauthorized:
      type: object
      properties:
        codigoRetorno:
          description: Return Code
          type: integer
          example: 4
        mensagem:
          description: Description return code
          example: Acesso nao autorizado ao conteudo pesquisado - (meaning Unauthorized Access)
          type: string
